services:
  trade_crawler:
    build:
      context: ./trade_crawler
      dockerfile: Dockerfile
    image: trade_crawler
    container_name: trade_crawler
    expose:
      - "9000"
    env_file:
      - ./trade_crawler/.env.production
    ports:
      - "9000:9000"

  trade_webserver:
    image: nginx:latest
    container_name: trade_nginx
    ports:
      - "80:80"
    volumes:
      - ./trade_webserver/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./trade_webserver/conf.d:/etc/nginx/conf.d:ro
      - ./trade_webserver/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - trade_crawler

  trade_worker:
    build:
      context: ./trade_crawler
      dockerfile: Dockerfile
    image: trade_worker
    container_name: trade_worker
    volumes:
      - ./trade_crawler:/var/www/html
    depends_on:
      - mongodb
      - trade_crawler
    env_file:
      - ./trade_crawler/.env.production
    command: php artisan queue:work --tries=3 --timeout=90
    
  mongodb:
    image: mongo:latest
    container_name: trade_mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./trade_crawler/.env.production
    volumes:
      - ./mongodb:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/data
  
  # trade_puppeteer:
  #   build: ./trade_puppeteer
  #   container_name: trade_puppeteer
  #   image: trade_puppeteer
  #   expose:
  #     - "4000"
  #   env_file:
  #     - ./trade_puppeteer/.env.production
  #   ports:
  #     - "4000:4000"
